name: dataextractor_analyzer
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  syncfusion_flutter_datagrid: ^28.1.36
  image_picker: ^1.1.2
  image: ^4.5.2
  google_mlkit_text_recognition: ^0.14.0
  path_provider: ^2.1.5
  sqflite: ^2.4.1
  pdf: ^3.11.3
  permission_handler: ^11.4.0
  google_fonts: ^6.2.1
  intl: ^0.20.2
  another_flushbar: ^1.12.30
  open_filex: ^4.7.0
  image_cropper: ^9.0.0
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.6
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_launcher_icons: "^0.14.3"
  flutter_native_splash: ^2.4.6
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# Add this section to override problematic dependencies
#dependency_overrides:
#  webview_flutter_android:
#  webview_flutter_wkwebview:

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/data_extarct_icons.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/fonts/Roboto-Regular.ttf
    - assets/fonts/Roboto-Bold.ttf